services:
  yazio-bot-api:
    build: .
    container_name: yazio_bot_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    # Si n8n est sur un réseau spécifique, décommentez et adaptez ci-dessous :
    # networks:
    #   - n8n_default

    # networks:
    #   n8n_default:
    #     external: true
